AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-core specific exceptions
#
Lint/MissingSuper: { Exclude: ['lib/ronin/core/params/types/*.rb'] }
Style/CaseEquality: { Exclude: ['lib/ronin/web/server/conditions.rb'] }
Style/EmptyMethod:
  Exclude:
    - 'lib/ronin/core/cli/shell.rb'
    - 'spec/**/*'

Style/GlobalStdStream:
  Exclude:
    - 'lib/ronin/core/cli/ruby_shell.rb'
    - 'spec/cli/ruby_shell_spec.rb'

Layout/HeredocIndentation: { Exclude: ['lib/ronin/core/cli/banner.rb'] }
Layout/ClosingHeredocIndentation: { Exclude: ['lib/ronin/core/cli/banner.rb'] }
